# Under the plugin folder, data is stored under /data/TagGame.db in a SQLite database.
# This option controls whether the plugin will add new rows to the TagLog table in this
# database whenever a player is tagged.
#
# The plugin does not currently use this data in any way, and it's not need for it to function.
# This feature exists for if you want to export the logs as a spreadsheet later on and calculate
# for how long each player was it or something like that.
log-tag-events-to-db: false
