name: CheezSurvTagGame
version: '${project.version}'
main: io.github.seriousguy888.cheezsurvtaggame.CheezSurvTagGame
api-version: 1.20
authors: [ SeriousGuy888 ]
description: just a plugin to play tag on an smp

softdepend: [ DiscordSRV ]

commands:
  survtag:
    description: Admin command for managing SurvTag.
    permission: survtag.admin
  it:
    description: See who is currently It in the game of tag, or set who is It if you have perms.
    permission: survtag.it
  tagstats:
    description: See your stats or the stats of other players in the game of tag.
    permission: survtag.stats
  taghud:
    description: Toggle whether you want to see the Tag HUD.
    permission: survtag.hud
  tagrules:
    description: See the rules of the game.
    permission: survtag.rules

permissions:
  survtag.admin:
    description: Allows access to the /survtag reload command.
    default: op
  survtag.it:
    description: Allows a player to use /it to check who is currently it.
    default: true
    children:
      survtag.it.set: false
  survtag.it.set:
    description: Allows a player to use /it <player> to manually set another player as being it.
    default: op
  survtag.stats:
    description: Allows a player to use /tagstats to see their own stats or those of another player.
    default: true
  survtag.hud:
    description: |
      Whether players can use the /taghud command to toggle seeing the HUD
      (the bossbar that provides info about who is it)
    default: true
    children:
      survtag.hud.others: false
  survtag.hud.others:
    description: Allows a player to toggle the Tag HUD for another player.
    default: op
  survtag.rules:
    description: Allows a player to see what the current rules are.
    default: true
    children:
      survtag.rules.modify: false
  survtag.rules.modify:
    description: Allows a player to use the /tagrules command to modify the rules of the game.
    default: op