name: CheezSurvTagGame
version: '${project.version}'
main: io.github.seriousguy888.cheezsurvtaggame.CheezSurvTagGame
api-version: 1.20
authors: [ SeriousGuy888 ]
description: just a plugin to play tag on an smp
commands:
  it:
    description: See who is currently It in the game of tag, or set who is It if you have perms.
  tagstats:
    description: See your stats or the stats of other players in the game of tag.